import csv
import os
import sys
from openpyxl import Workbook
from openpyxl.styles import Font, numbers



# Converts CSV generated by America First Credit union into a standard file format that I use to apply to my finances spreadsheet

def convertAFCUToStandardFormat(input_file):
    print("Converting...")

    # Get the directory and base filename of the input file
    directory = os.path.dirname(input_file)
    base_filename = os.path.splitext(os.path.basename(input_file))[0]
    output_file = os.path.join(directory, f"{base_filename}_converted.xlsx").replace("\\", "/")

    # Create a new Excel workbook
    wb = Workbook()
    ws = wb.active
    ws.title = "Expenses"

    # Write headers
    headers = ["Expense", "Amount", "Date"]
    ws.append(headers)

    with open(input_file, mode="r", newline="", encoding="utf-8") as infile:
        reader = csv.reader(infile)
        header = next(reader)  # Read and discard the header row

        # Identify column indices (case-insensitive search)
        try:
            date_idx = header.index("Date")
            desc_idx = header.index("Description")
            debit_idx = header.index("Debit")
            credit_idx = header.index("Credit")
        except ValueError:
            # Failsafe in case I use the wrong file
            print("Error: Input CSV must contain 'Date', 'Description', 'Debit', and 'Credit' columns.")
            sys.exit(1)

        data_rows = []
        for row in reader:
            try:
                # Read values, defaulting empty cells to "0"
                date = row[date_idx]
                expense = row[desc_idx]
                debit = row[debit_idx] if row[debit_idx] else ""
                credit = row[credit_idx] if row[credit_idx] else ""

                # Determine if it's a debit (negative value originally)
                is_debit = bool(debit)
                amount = float(debit.strip('-')) if is_debit else float(credit)
                data_rows.append([expense, amount, date, is_debit])
            except (IndexError, ValueError):
                print(f"Skipping malformed row: {row}")

    # Write data to the worksheet
    for row_data in data_rows:
        expense, amount, date, is_debit = row_data
        new_row = ws.append([expense, amount, date])

    # Apply formatting
    for row in ws.iter_rows(min_row=2, min_col=2, max_col=2):
        for cell in row:
            cell.number_format = numbers.FORMAT_CURRENCY_USD_SIMPLE
            if isinstance(cell.value, (int, float)):
                row_index = cell.row - 2  # Adjust for 0-based index in data_rows
                if data_rows[row_index][3]:  # Check if it was a debit
                    cell.font = Font(color="FF0000")  # Red for expenses (debits)
                else:
                    cell.font = Font(color="008000")  # Green for earnings (credits)

    wb.save(output_file)
    print(f"Converted file saved to: {output_file}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python afcu.py inputfilelocation.csv")
        print("Note: This only works with CSVs generated by America First Credit Union")
        sys.exit(1)

    input_csv = sys.argv[1]
    convertAFCUToStandardFormat(input_csv)
